version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sql_network
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  sql_data:
    name: sql_server_data

networks:
  sql_network:
    name: sql_server_network
    driver: bridge